[workspace]
members = [
    "dnas/val_democracy/zomes/integrity",
    "dnas/val_democracy/zomes/coordinator",
]
resolver = "2"

[workspace.dependencies]
hdi = "=0.7.0"
hdk = "=0.6.0"
serde = "1"
holochain_serialized_bytes = "=0.0.56"
