[package]
name = "val_democracy_coordinator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk.workspace = true
serde.workspace = true
val_democracy_integrity = { path = "../integrity" }
